### ISSUE TITLE
Unable to jump normally with mod enabled

### ISSUE THREAD

**Issue by leakspokemon** [harshavb/webfishing-mods#2] opened 2024-11-12 00:49 UTC
I'm sure this might be intended, but some areas become inaccessible with the mod installed due to not being able to jump normally. Furthermore, trying to get up from sitting tends to launch you forward sometimes. It would be nice if you could toggle the slide on and off in order to jump normally again. Very fun mod otherwise!!

**Comment by harshavb** [comment] 2024-11-12 16:22
Closing as duplicate of #1 (not your fault, I should've kept that open)

**Closed as completed** 2024-11-12 16:23 UTC
